/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LibraryJobIdRouteImport } from './routes/library.$jobId'
import { Route as ApiPublicDownloadSelectedRouteImport } from './routes/api/public/download-selected'
import { Route as ApiPublicDownloadAllRouteImport } from './routes/api/public/download-all'
import { Route as ApiPublicRunJobJobIdRouteImport } from './routes/api/public/run-job.$jobId'
import { Route as ApiPublicReenrichJobIdRouteImport } from './routes/api/public/reenrich.$jobId'
import { Route as ApiPublicDownloadJobIdRouteImport } from './routes/api/public/download.$jobId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryJobIdRoute = LibraryJobIdRouteImport.update({
  id: '/$jobId',
  path: '/$jobId',
  getParentRoute: () => LibraryRoute,
} as any)
const ApiPublicDownloadSelectedRoute =
  ApiPublicDownloadSelectedRouteImport.update({
    id: '/api/public/download-selected',
    path: '/api/public/download-selected',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicDownloadAllRoute = ApiPublicDownloadAllRouteImport.update({
  id: '/api/public/download-all',
  path: '/api/public/download-all',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicRunJobJobIdRoute = ApiPublicRunJobJobIdRouteImport.update({
  id: '/api/public/run-job/$jobId',
  path: '/api/public/run-job/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReenrichJobIdRoute = ApiPublicReenrichJobIdRouteImport.update({
  id: '/api/public/reenrich/$jobId',
  path: '/api/public/reenrich/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDownloadJobIdRoute = ApiPublicDownloadJobIdRouteImport.update({
  id: '/api/public/download/$jobId',
  path: '/api/public/download/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/library/$jobId': typeof LibraryJobIdRoute
  '/api/public/download-all': typeof ApiPublicDownloadAllRoute
  '/api/public/download-selected': typeof ApiPublicDownloadSelectedRoute
  '/api/public/download/$jobId': typeof ApiPublicDownloadJobIdRoute
  '/api/public/reenrich/$jobId': typeof ApiPublicReenrichJobIdRoute
  '/api/public/run-job/$jobId': typeof ApiPublicRunJobJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/library/$jobId': typeof LibraryJobIdRoute
  '/api/public/download-all': typeof ApiPublicDownloadAllRoute
  '/api/public/download-selected': typeof ApiPublicDownloadSelectedRoute
  '/api/public/download/$jobId': typeof ApiPublicDownloadJobIdRoute
  '/api/public/reenrich/$jobId': typeof ApiPublicReenrichJobIdRoute
  '/api/public/run-job/$jobId': typeof ApiPublicRunJobJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/bootstrap': typeof BootstrapRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/library': typeof LibraryRouteWithChildren
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/library/$jobId': typeof LibraryJobIdRoute
  '/api/public/download-all': typeof ApiPublicDownloadAllRoute
  '/api/public/download-selected': typeof ApiPublicDownloadSelectedRoute
  '/api/public/download/$jobId': typeof ApiPublicDownloadJobIdRoute
  '/api/public/reenrich/$jobId': typeof ApiPublicReenrichJobIdRoute
  '/api/public/run-job/$jobId': typeof ApiPublicRunJobJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/reset-password'
    | '/library/$jobId'
    | '/api/public/download-all'
    | '/api/public/download-selected'
    | '/api/public/download/$jobId'
    | '/api/public/reenrich/$jobId'
    | '/api/public/run-job/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/reset-password'
    | '/library/$jobId'
    | '/api/public/download-all'
    | '/api/public/download-selected'
    | '/api/public/download/$jobId'
    | '/api/public/reenrich/$jobId'
    | '/api/public/run-job/$jobId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/forgot-password'
    | '/library'
    | '/login'
    | '/reset-password'
    | '/library/$jobId'
    | '/api/public/download-all'
    | '/api/public/download-selected'
    | '/api/public/download/$jobId'
    | '/api/public/reenrich/$jobId'
    | '/api/public/run-job/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  BootstrapRoute: typeof BootstrapRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LibraryRoute: typeof LibraryRouteWithChildren
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiPublicDownloadAllRoute: typeof ApiPublicDownloadAllRoute
  ApiPublicDownloadSelectedRoute: typeof ApiPublicDownloadSelectedRoute
  ApiPublicDownloadJobIdRoute: typeof ApiPublicDownloadJobIdRoute
  ApiPublicReenrichJobIdRoute: typeof ApiPublicReenrichJobIdRoute
  ApiPublicRunJobJobIdRoute: typeof ApiPublicRunJobJobIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library/$jobId': {
      id: '/library/$jobId'
      path: '/$jobId'
      fullPath: '/library/$jobId'
      preLoaderRoute: typeof LibraryJobIdRouteImport
      parentRoute: typeof LibraryRoute
    }
    '/api/public/download-selected': {
      id: '/api/public/download-selected'
      path: '/api/public/download-selected'
      fullPath: '/api/public/download-selected'
      preLoaderRoute: typeof ApiPublicDownloadSelectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download-all': {
      id: '/api/public/download-all'
      path: '/api/public/download-all'
      fullPath: '/api/public/download-all'
      preLoaderRoute: typeof ApiPublicDownloadAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/run-job/$jobId': {
      id: '/api/public/run-job/$jobId'
      path: '/api/public/run-job/$jobId'
      fullPath: '/api/public/run-job/$jobId'
      preLoaderRoute: typeof ApiPublicRunJobJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/reenrich/$jobId': {
      id: '/api/public/reenrich/$jobId'
      path: '/api/public/reenrich/$jobId'
      fullPath: '/api/public/reenrich/$jobId'
      preLoaderRoute: typeof ApiPublicReenrichJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/download/$jobId': {
      id: '/api/public/download/$jobId'
      path: '/api/public/download/$jobId'
      fullPath: '/api/public/download/$jobId'
      preLoaderRoute: typeof ApiPublicDownloadJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LibraryRouteChildren {
  LibraryJobIdRoute: typeof LibraryJobIdRoute
}

const LibraryRouteChildren: LibraryRouteChildren = {
  LibraryJobIdRoute: LibraryJobIdRoute,
}

const LibraryRouteWithChildren =
  LibraryRoute._addFileChildren(LibraryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  BootstrapRoute: BootstrapRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LibraryRoute: LibraryRouteWithChildren,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiPublicDownloadAllRoute: ApiPublicDownloadAllRoute,
  ApiPublicDownloadSelectedRoute: ApiPublicDownloadSelectedRoute,
  ApiPublicDownloadJobIdRoute: ApiPublicDownloadJobIdRoute,
  ApiPublicReenrichJobIdRoute: ApiPublicReenrichJobIdRoute,
  ApiPublicRunJobJobIdRoute: ApiPublicRunJobJobIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
