
ALTER TABLE public.scrape_results
  ADD COLUMN IF NOT EXISTS email TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS facebook TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS instagram TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS twitter TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS youtube TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS tiktok TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS snapchat TEXT DEFAULT '';
